### ISSUE TITLE
TAP format support

### ISSUE THREAD

**Issue by igor-ivanov** [Mellanox/ci-demo#21]
## Feature request:

Is it possible to support TAP format view as a result of job.
Something like http://hpc-master.lab.mtl.com:8080/job/sockperf-pipeline/133/tapTestReport/
or
https://medium.com/@silviachen_76118/tap-plugin-in-jenkins-pipeline-d48060652faa
https://stackoverflow.com/a/44704844

**Comment by mike-dubman** [comment]
added - please see example here: https://github.com/Mellanox/ci-demo/blob/master/.ci/examples/job_matrix_tap.yaml

**Comment by igor-ivanov** [comment]
:+1
Worked
