### ISSUE TITLE
Resource allocation

### ISSUE THREAD

**Issue by lennybe** [Mellanox/ci-demo#52]
Hi,
I am building UFM on 4 distros in parallel on K8s, but need to install them on BareMetal machines
https://github.com/Mellanox/UFM/blob/master/.ci/matrix_job_runci.yaml#L24
https://github.com/Mellanox/UFM/blob/master/.ci/matrix_job_runci.yaml#L31

what is the proper way to do it? so BM will be allocated when build is done and will not wait in busy loop.

**Comment by mike-dubman** [comment]
please see https://docs.openstack.org/infra/jenkins-job-builder/triggers.html ```build-result``` command
lets talk to see it through

**Comment by lennybe** [comment]
solution provided by 
https://github.com/Mellanox/ci-demo/commit/5d13d9aa5fd7dcc7b4ccbb6bd3c1c0fcbd900710
