### ISSUE TITLE
VMA/XLIO CI is broken

### ISSUE THREAD

**Issue by igor-ivanov** [Mellanox/ci-demo#57]
Starting http://hpc-master.lab.mtl.com:8080/job/LibXLIO/308/
any jenkins job takes 20s and fails
```
[Pipeline] End of Pipeline
ERROR: config failed with msg: Step='Service' has both containerSelector and agentSelector configured, while it is mutual exclusive, setup global `step_allow_single_selector: false` to disable
Adding one-line test results to commit status...
Setting status of a6cb3b35a99e4e9b9a2b3a1e715849df3439e78b to FAILURE with url http://hpc-master.lab.mtl.com:8080/job/LibXLIO/308/ and message: '[FAIL]
 No test results found.'
Using context: Mellanox Lab
Finished: FAILURE
```

**Suspicious** actions:
https://github.com/Mellanox/ci-demo/commit/fae5bc562f16f2a167da1548fa6d24aea17538f5

**Comment by igor-ivanov** [comment]
Descriprion about expected:

step is configured to be launched on 
```
    agentSelector:
      - "{name: 'compiler', category: 'tool'}"
```
https://github.com/Mellanox-lab/libxlio/blob/master/.ci/matrix_job.yaml#L175-L182
but in fact
this step is executed on all containers and bare metal nodes (http://hpc-master.lab.mtl.com:8080/blue/organizations/jenkins/LibXLIO/detail/LibXLIO/326/pipeline)
Expected processing can be seen http://hpc-master.lab.mtl.com:8080/blue/organizations/jenkins/LibXLIO/detail/LibXLIO/324/pipeline/

**Comment by vasily-v-ryabov** [comment]
Looks like it is the fix: https://github.com/Mellanox/ci-demo/commit/4d12f1952056e86a1f37cbd692c65ffe55d2de28

**Comment by vasily-v-ryabov** [comment]
@mike-dubman part of issue still exists. Please read the latest comment from Igor.

**Comment by mike-dubman** [comment]
Need to add following to yaml file to request old behave
```
step_allow_single_selector: true
```

**Comment by igor-ivanov** [comment]
The issue can be resolved using
``` 
   containerSelector:
      - "{name: 'skip-container'}"
    agentSelector:
      - "{nodeLabel: 'r-aa-fatty09'}"
```
